# Generated by Django 3.2.7 on 2021-10-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Strategy name')),
                ('shares_limit_high', models.PositiveSmallIntegerField(verbose_name='Shares amount limit to store')),
                ('shares_limit_low', models.SmallIntegerField(verbose_name='Shares amount limit to borrow')),
                ('buy', models.PositiveSmallIntegerField(verbose_name='Shares amount to buy if success')),
                ('sell', models.PositiveSmallIntegerField(verbose_name='Shares amount to sell if failure')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.ImageField(upload_to='plots/%Y/%m/%d/%H/%M/%S')),
                ('share_delta', models.FloatField()),
                ('balance_delta', models.FloatField()),
                ('share', models.CharField(max_length=255)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.strategy')),
            ],
        ),
    ]
