# Generated by Django 3.2.7 on 2022-02-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plots/%Y/%m/%d/%H/%M/%S')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Strategy name')),
                ('shares_limit_high', models.PositiveSmallIntegerField(verbose_name='Shares amount limit to store')),
                ('shares_limit_low', models.SmallIntegerField(verbose_name='Shares amount limit to borrow')),
                ('buy', models.PositiveSmallIntegerField(verbose_name='Shares amount to buy if success')),
                ('sell', models.PositiveSmallIntegerField(verbose_name='Shares amount to sell if failure')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval_start', models.DateField()),
                ('time_interval_end', models.DateField()),
                ('price_deltas', models.JSONField()),
                ('balance_plot', models.ImageField(upload_to='plots/%Y/%m/%d/%H/%M/%S')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.portfolio')),
                ('share_plots', models.ManyToManyField(related_name='log_share_plots', to='ui.Image')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.strategy')),
            ],
        ),
    ]
