# Generated by Django 3.2.7 on 2021-10-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time_interval_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='time_interval_start',
            field=models.DateField(null=True),
        ),
    ]
