# Generated by Django 3.2.7 on 2021-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20211006_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='balance_delta',
        ),
        migrations.RemoveField(
            model_name='log',
            name='share_delta',
        ),
        migrations.AddField(
            model_name='log',
            name='balance_delta_money',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='balance_delta_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='share_delta_money',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='share_delta_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_interval_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_interval_start',
            field=models.DateField(),
        ),
    ]
