# Generated by Django 3.2.7 on 2022-02-11 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ui', '0003_auto_20211006_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('quotes', models.JSONField()),
                ('price_plot', models.ImageField(upload_to='plots')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('quote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quotes.quote')),
                ('amount', models.IntegerField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_origin', to='quotes.quote')),
            ],
            bases=('quotes.quote',),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('balance', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logs', models.ManyToManyField(related_name='portfolio_logs', to='ui.Log')),
                ('shares', models.ManyToManyField(related_name='portfolio_shares', to='quotes.Share')),
            ],
        ),
    ]
