# Generated by Django 3.2.7 on 2022-02-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ui', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='logs',
            field=models.ManyToManyField(related_name='portfolio_logs', to='ui.Log'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='shares',
            field=models.ManyToManyField(related_name='portfolio_shares', to='quotes.Share'),
        ),
    ]
